name: Build and Deploy WebGL

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

jobs:
  build:
    name: Build Unity Project
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true

      # Cache Library folder
      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-WebGL
          restore-keys: |
            Library-

      # Build WebGL
      - name: Unity - Builder
        uses: game-ci/unity-builder@v3
        with:
          targetPlatform: WebGL
          unityVersion: 2021.3.23f1
          buildsPath: build
          buildName: WebGL
          allowDirtyBuild: true

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/WebGL
          branch: gh-pages
