name: Build and Deploy WebGL

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    name: Build Unity WebGL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Library folder
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-WebGL-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-WebGL-
            Library-

      - name: Build WebGL
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: WebGL
          buildName: Build
          versioning: Semantic
          customParameters: -disable-compression

      - name: List build directory
        run: |
          echo "Build directory contents:"
          ls -R build/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build-WebGL
          path: build/WebGL
          retention-days: 1

  deploy:
    needs: build
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: Build-WebGL
          path: build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/Build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
