name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Unity
        uses: game-ci/unity-builder@v2
        with:
          projectPath: .
          buildTarget: WebGL
          unityVersion: 2021.3.23f1
          outputPath: Builds/WebGL

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Builds/WebGL
          publish_branch: gh-pages # Change if you want a different branch for GitHub Pages
