name: Deploy Unity WebGL to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Build Unity Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            Library/ScriptAssemblies
            Library/shadercache
          key: ${{ runner.os }}-unity-cache-${{ hashFiles('Packages.lock.json') }}
      - uses: game-ci/unity-builder@v4
      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/WebGL/Build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
