name: Build and Deploy WebGL

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Unity Project
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true

      # Cache Library folder
      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-WebGL-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-WebGL-
            Library-

      # Build WebGL
      - name: Unity - Build WebGL
        uses: game-ci/unity-builder@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          unityVersion: 2021.3.23f1
          buildName: WebGL
          buildsPath: Build
          allowDirtyBuild: true

      # Deploy the entire WebGL build folder
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: Build/WebGL # This should contain index.html and all other build files
          branch: gh-pages
          clean: true # Automatically remove deleted files from the deploy branch
